version: "3.8"
services:
  db:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
    driver: local
