import { type NextPage } from "next";
import { IoReorderThreeOutline } from "react-icons/io5";
import { AiOutlineBell } from "react-icons/ai";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Flex, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-full flex-col ">
        <header className="flex h-14 w-full items-center justify-around border-b border-gray-200 text-2xl">
          <div>
            <IoReorderThreeOutline />
          </div>
          <Text fontWeight="thin" fontSize="2xl">
            Title Here
          </Text>
          <div className="flex items-center gap-1 space-x-2">
            <div>
              <AiOutlineBell />
            </div>
            <div>
              <AiOutlineBell />
            </div>
          </div>
        </header>
        <section className="grid grid-cols-12 place-items-center w-full h-full">
          <main className="col-span-8 h-full w-full border-r border-gray-300">
            Body
          </main>
          <aside className="col-span-4 w-full h-full">Body 123232</aside>
        </section>
      </div>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <Text color="white">Hello World</Text>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
