import Head from "next/head";
import { Box } from "@chakra-ui/react";
import type { ReactElement } from "react";
import { useSession } from "next-auth/react";

import Loading from "./loading";
import { GithubButton, LogoutButton } from "@/components/buttons";

const Layout = ({ children }: { children: ReactElement }) => {
  const { data: sessionData, status } = useSession();

  if (status === "loading") {
    return <Loading status="Initializing Session." />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-full flex-col ">
        <header className="flex h-14 w-full items-center justify-around border-b border-gray-200 text-2xl">
          <div className="flex-grow"></div>
          <Box mx={5}>
            {sessionData && <LogoutButton />}

            {!sessionData && <GithubButton />}
          </Box>
        </header>
        <section className="w-fullplace-items-center h-full">
          <main className="h-full w-full ">{children}</main>
        </section>
      </div>
    </>
  );
};

export default Layout;
