import type { ReactElement } from "react";
import { IoReorderThreeOutline } from "react-icons/io5";
import { AiOutlineBell } from "react-icons/ai";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Flex, Text } from "@chakra-ui/react";

const Layout = ({ children }: { children: ReactElement }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-full flex-col ">
        <header className="flex h-14 w-full items-center justify-around border-b border-gray-200 text-2xl">
          <div>
            <IoReorderThreeOutline />
          </div>
          <div className="text-2xl font-thin">Title Here</div>
          <div className="flex items-center gap-1 space-x-2">
            <div>
              <AiOutlineBell />
            </div>
            <div>
              <AiOutlineBell />
            </div>
          </div>
        </header>
        <section className="grid h-full w-full grid-cols-12 place-items-center">
          <main className="col-span-8 h-full w-full border-r border-gray-300">
            {children}
          </main>
          <aside className="col-span-4 h-full w-full">Aside</aside>
        </section>
      </div>
    </>
  );
};

export default Layout;
